### DISCUSSION TITLE
Exporting from GitHub Actions not working

### DISCUSSION THREAD

**Discussion by ispringle** [kaushalmodi/ox-hugo#711] [Q&A]
I'm attempting to use GH actions to export. I'd rather not have to do something on my side (generate md files) to get my site working. I found a SO answer that gave me this elisp script: 
```lisp
(defvar 0x44/package-archives
  (list
   (cons "melpa-stable" "https://stable.melpa.org/packages/")
   (cons "melpa" "https://melpa.org/packages/")
   (cons "gnu" "https://elpa.gnu.org/packages/")))

(defvar 0x44/packages-to-install '(ox-hugo))

(defun 0x44/designate-package-site (site)
  (message "Designating package site %s => %s" (car site) (cdr site))
  (add-to-list 'package-archives site t))

(defun 0x44/designate-package-sites ()
  (message "Designating package sites")
  (mapcar #'0x44/designate-package-site 0x44/package-archives))

(defun 0x44/install-package (pkg)
  (message "Installing package %s" pkg)
  (ignore-errors (package-install pkg)))

(when (locate-library "package")
  (require 'package)
  (0x44/designate-package-sites)
  (package-initialize)
  (unless package-archive-contents (package-refresh-contents))
  (mapcar #'0x44/install-package 0x44/packages-to-install))

(defun 0x44/batch-ox-hugo-file (file)
  (message "Exporting org subtrees to hugo from %s" file)
  (let ((all-subtrees t)
    (any-visibility nil))
    (with-current-buffer (find-file-noselect file)
      (org-hugo-export-wim-to-md all-subtrees any-visibility))))

(defun 0x44/batch-ox-hugo-directory (directory)
  (message "Exporting all org subtrees in all files in %s" directory
  (let ((default-directory (expand-file-name directory)))
    (mapcar #'0x44/batch-ox-hugo-file
        (append (file-expand-wildcards "**.org")
                (file-expand-wildcards "**/*.org"))))))

(setq org-export-with-broken-links t)
(0x44/batch-ox-hugo-directory default-directory)
```

And I have then paired that with my Gh workflow:
```yaml
# [[file:../../github-workflow.org::*Triggers][Triggers:1]]
name: GitHub Actions Production Deployment

on:
  push:
    branches:
      - master
# Triggers:1 ends here
# [[file:../../github-workflow.org::*Triggers][Triggers:2]]
  workflow_dispatch:
# Triggers:2 ends here
# [[file:../../github-workflow.org::*Jobs][Jobs:1]]
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
# Jobs:1 ends here
# [[file:../../github-workflow.org::*Checkout and Cleanup][Checkout and Cleanup:1]]
      - name: Checkout org
        uses: actions/checkout@v2
# Checkout and Cleanup:1 ends here
# [[file:../../github-workflow.org::*Checkout and Cleanup][Checkout and Cleanup:2]]
      - name: "Remove files marked :PRIVATE: t"
        run: 'find ./ -type f -exec grep -q "^:PRIVATE: t\$" {} \; -delete'
# Checkout and Cleanup:2 ends here
# [[file:../../github-workflow.org::*Build and Deploy!][Build and Deploy!:1]]
      - name: Install emacs
        uses: purcell/setup-emacs@master
        with:
          version: 28.2
      - name: Compile org files to markdown
        run: emacs -q --batch -l export-hugo.el
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.110.0
      - name: Build the site
        run: hugo --minify
        working-directory: ./site/
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          dist_dir: site/public
# Build and Deploy!:1 ends here
```
 
This results in the error (abbr. the output is like 40 lines):
```
Debugger entered--Lisp error: (org-link-broken "e1a06552-0ed0-4320-a955-a1610f5a0382")
  signal(org-link-broken ("e1a06552-0ed0-4320-a955-a1610f5a0382"))
  org-export-resolve-id-link((link ... ...) (:parse-tree ... :export-options nil :back-end hugo :translate-alist ... :exported-data #<hash-table eq 0/4001 0x4e845201> :input-buffer "blog.org" :input-file "/Users/IPringl..." ...))
...
```

It seems that somehow my links are not working. I have verified that the linked referred is valid and that the file being linked by that ID is also present in the ox-hugo export. I have also verified that ox-hugo will happily build this when it is on my machine in my emacs setup. So I'm thinking that for some reason my elisp script is not providing org-mode/ox-huge enough information to properly identify the location of the linked file. You'll notice I've added the broken-links option to the script (also in my files) and it's not working, so I think maybe this is different than the similar issues I've found here before.
