### ISSUE TITLE
Support setting "resources" in front-matter

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#115]
This feature is upcoming in Hugo v0.33 (https://github.com/gohugoio/hugo/commit/20c9b6ec81171d1c586ea31d5d08b40b0edaffc6).

Example front-matter:

```
+++
date = 2017-01-17
title = "My Bundle With TOML Resource Metadata"
layout = "bundle-resource-meta"

[[resources]]
# The order matters
src = "image-4.png"
title = "TOML: The Fourth Image"
[[resources]]
src = "*.png"
name = "my-cool-image-:counter"
title = "TOML: The Image #:counter"
[resources.params]
byline = "bep"
+++
```

```
---
date: 2017-01-17
title: My Bundle With YAML Resource Metadata
layout: bundle-resource-meta
resources:
# The order matters
- src: "image-4.png"
  title: "The Fourth Image"
- src: "*.png"
  name: "my-cool-image-:counter"
  title: "The Image #:counter"
  params:
    byline: "bep"
---
```

```
---
title: "Bundle Galore"
slug: pageslug
date: 2017-10-09
resources:
- src: "*.jpg"
  name: "my-sunset-:counter"
  title: "Sunset Galore :counter"
  params:
    myParam: "My Sunny Param"
---
```

- http://hugotest.bep.is/resourcemeta/bundle-with-resource-meta-toml/
- http://hugotest.bep.is/resourcemeta/bundle-with-resource-meta-yaml/
