### ISSUE TITLE
allow menu front matter specific to a 'post'/Org subtree

### ISSUE THREAD

**Issue by titaniumbones** [kaushalmodi/ox-hugo#19]
The YAML syntax for Hugo menu placement is: 

menu:
    main:
         parent: articles
         [etc]

Do we have a way to gneerate this kind of multilevel metadata? If not, we should have one...

**Comment by kaushalmodi** [comment]
I didn't follow that.

Isn't the menu configuration done in `config.toml` or `config.yaml`?

Or did you mean that you'd like to specify the destination subdir for each subtree?

Example:

```
#+TITLE: My blog
* Posts 
These go to <blog root dir>/posts/
** Post 1
This goes to <blog root dir>/posts/post1.md
* Articles 
These go to <blog root dir>/articles/
** Article 1
This goes to <blog root dir>/articles/article1.md
```

**Comment by titaniumbones** [comment]
I have a particular use-case in mind. 

For my courses, I maintian about 3-5 org source files, e.g., "course Details", "Labs", "Assignments".  Then, for each assignment, I I maintian a subtree. So `Assignments.org` might have the structure:
```org-mode
* Short Paper 1
* Book Review
* Final Essay
```
Each of these should probably be a **child** menu item of the `Assignments` parent menu item.  Ideally, this information would be stored (a) in the org-mode properties drawer, and then (b) in the front matter of each post.  THis keeps all the rlevant information in the org source files.  Otherwise `config.toml` (or `.yaml`) will easily get out of sync with the actual files.

Unfortunately, the yaml and toml syntax for storing complex data objects like these hash tables/dictionaries is difficult to reproduce:
```yaml
menu: 
    main:
        parent: assignments
        weight: -100
```
I'm not quite sure even how this is supposed to be represeented in TOML.  

Anyway, it would be really nice to be able to automate some of this. And I think it's not just me who would like to be able to do that.  

Does this make more sense?

Hugo menu docs are here: https://gohugo.io/extras/menus

**Comment by titaniumbones** [comment]
so, basically I'm confirming your example.

**Comment by kaushalmodi** [comment]
> Unfortunately, the yaml and toml syntax for storing complex data objects like these hash tables/dictionaries is difficult to reproduce:

```yaml
menu: 
    main:
        parent: assignments
        weight: -100
```

Correct. But that menu hierarchy will be pretty much static once your site structure stabilizes. And then may be need adding/removing/moving the menu section once in a while. Is that right?

My concern is that the `config.toml` contains many things which the user might tweak from time to time. We do not want `ox-hugo` to unknowingly butcher user settings.. basically *don't update the same file manually as well as automatically*. And if we do it completely automatically, then what you said verbatim here ( https://github.com/kaushalmodi/ox-hugo/issues/20#issuecomment-312366826 ) :)

> This would get one closer to automating the construction of a whole hugo site directly from org.

---

> I'm not quite sure even how this is supposed to be represeented in TOML.

It would look something like this in TOML:

```toml
[[menu.main]]
parent = "Assignments"
weight = -100

[[menu.main]]
parent = "Labs"
weight = 1
```

> Anyway, it would be really nice to be able to automate some of this. 

Definitely. Then we need to generate the whole `config.toml` from scratch on each export ( https://github.com/kaushalmodi/ox-hugo/issues/20 )

**Comment by titaniumbones** [comment]
> Definitely. Then we need to generate the whole config.toml from scratch on each export ( #20 )

Not necessarily, since it's possible to add the individual menu items in the frontmatter of each post.  In fact ,this is how the hugo docs manage things: 
https://github.com/gohugoio/hugoDocs

here's an example: 
https://github.com/gohugoio/hugoDocs/blob/master/content/overview/configuration.md


full YAML for the above:
```YAML
---
aliases:
- /doc/configuration/
lastmod: 2016-09-17
date: 2013-07-01
linktitle: Configuration
menu:
  main:
    parent: getting started
next: /overview/source-directory
toc: true
prev: /overview/usage
title: Configuring Hugo
weight: 40
```
