### ISSUE TITLE
Update docs on recommended `config.toml` if using Hugo v0.60+

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#307]
Users will **need** to have this in their Hugo site `config.toml`:

```toml
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```

This setting enables rendering of inline HTML in the Markdown content files. It is needed because ox-hugo exports table captions, user specified HTML attibutes, small CSS snippets, export_html blocks, etc. as inline HTML (there's no other way!).

Ref: https://gohugo.io/news/0.60.0-relnotes/
