### ISSUE TITLE
Code blocks exported from `src_foo` blocks know their language

### ISSUE THREAD

**Issue by pdcawley** [kaushalmodi/ox-hugo#638]
Given some org source like this:

```org-mode
Executing src_bash{sudo rm -rf /} is generally considered a foolish thing to do.
```

the current version of ox-hugo exports the following:

```markdown
Executing `sudo rm -rf /` is generally considered a foolish thing to do.
```

it would be immensely useful to me if the resulting markdown looked something like:

```markdown
Executing <code class='inline inline-bash'>sudo rm -rf /</code> is generally considered a foolish thing to do.
```

which allows me to distinguish in my stylesheets between actual code and generic code-ish stuff.

Essentially I want to be able to write, say:

```css
code.inline::before {
    color: initial;
    content: "｢";
}
code.inline::after {
    color: initial;
    content: "｣";
}
```

in my stylesheets and have only `src_foo{...}` blocks wrapped in corner brackets.
